---
# tasks file for monitor
- name: 创建监控路径
  file:
    mode: "0644"
    owner: ansible
    group: ansible
    state: directory
    path: "/opt/monitor"

- name: 复制相关软件包
  copy:
    src: { { item.file } }
    dest: { { item.dir } }
    loop:
      - { file: node_exporter_1.8.1, dir: /opt/monitor }
      - { file: "", dir }
      - { file: "", dir }
      - { file: "", dir }
  when: ipv4.net and item.file != grafana

- name: 创建相关文件夹
  file:
    mode: "0644"
    owner: ansible
    group: ansible
    state: directory
    path: "/opt/monitor/{{ item }}"
    loop:
      - node_exporter
      - mysqld_exporter
      - grafana
      - prometheus

- name: 下载相关软件包
  get_url:
    url: { { item.url } }
    dest: "/opt/monitor/{{ item.dir }}"
    loop:
      - { dir: node_exporter, url }
      - { dir: mysqld_exporter, url }
      - { dir: prometheus, url }
      - { dir: grafana, url }

- name: 复制相关软件包
  copy:
    src: { { item.file } }
    dest: { { item.dir } }
    loop:
      - { file: node_exporter_1.8.1, dir: /opt/monitor }
      - { file: "", dir }
      - { file: "", dir }
      - { file: "", dir }
